'use strict'

const { flatten, uniqBy } = require('lodash')

// Normalize OpenAPI security request parameters into specification-agnostic format
const getSecParams = function({
  spec: { securityDefinitions, security: apiSecurity = [] },
  operation: { security = apiSecurity },
}) {
  const secRefs = getSecRefs({ security })
  const secParams = secRefs.map(([secName, scopes]) =>
    getSecParam({ secName, scopes, securityDefinitions }),
  )
  return secParams
}

const getSecRefs = function({ security }) {
  const securityA = security.map(Object.entries)
  const securityB = flatten(securityA)
  const securityC = uniqBy(securityB, JSON.stringify)
  return securityC
}

// Retrieve among the `securityDefinitions`
const getSecParam = function({ secName, scopes, securityDefinitions }) {
  const securityDef = securityDefinitions[secName]
  const securityDefA = normalizeSecurityDef({ securityDef })
  return { ...securityDefA, secName, scopes }
}

// Normalize security to the same format as other parameters
const normalizeSecurityDef = function({ securityDef }) {
  const handler = getSecParamHandler(securityDef)
  const secParam = handler(securityDef)
  // Security parameters are not generated by default
  return { ...secParam, required: false }
}

const getSecParamHandler = function({ type }) {
  const handler = SECURITY_DEFS[type]
  if (handler !== undefined) {
    return handler
  }

  throw new Error(`Security definitions of type '${type}' are not implemented yet`)
}

// `apiKey` security definitions -> `header|query` request paramater
const getDefApiKey = function({ name, in: location }) {
  return { name, location, schema: { type: 'string' } }
}

const SECURITY_DEFS = {
  apiKey: getDefApiKey,
}

module.exports = {
  getSecParams,
}
