module.exports = {
  ...require('./types'),
  ...require('./promise'),
  ...require('./reduce'),
  ...require('./sort'),
  ...require('./location'),
  ...require('./simple_schema'),
  ...require('./flat'),
  ...require('./prefix'),
  ...require('./get'),
  ...require('./result'),
  ...require('./merge'),
  ...require('./crawl'),
  ...require('./search'),
  ...require('./path'),
  ...require('./json_pointer'),
  ...require('./string'),
  ...require('./cardinal'),
  // eslint-disable-next-line import/max-dependencies
  ...require('./regexp'),
}
